# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/c926e626-f324-4a25-a09c-a7b9e96f6a15";

  fileSystems."/home" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@home" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@nix" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/srv" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@srv" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@snaps" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/home/.snapshots" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@snaps_home" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/nix/.snapshots" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@snaps_nix" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@log" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/var/cache" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@cache" "autodefrag" "commit=120" "compress=zstd:5" "discard=async" "flushoncommit" "space_cache=v2" "ssd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BECD-AFB5";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
